//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Refectory_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Selection
    {
        public string id { get; set; }
        public System.DateTime dmDate { get; set; }
        public string dmType { get; set; }
        public string location { get; set; }
        public bool paid { get; set; }
    
        public virtual Daily_Menu Daily_Menu { get; set; }
        public virtual Users Users { get; set; }
    }
}
